name: Terraform 배포 요청
description: 환경에 맞춰 Terraform 리소스 배포를 요청합니다.
title: "[Terraform] 배포 요청 - 환경: dev"
labels: [terraform, provisioning, auto-deploy]
body:
  - type: input
    id: environment
    attributes:
      label: 🌍 환경 이름
      description: dev / stage / prod 중 하나
      placeholder: "dev"
    validations:
      required: true

  - type: input
    id: location
    attributes:
      label: 📍 Azure 지역 (location)
      placeholder: "koreacentral"
      description: Azure 리소스를 생성할 지역
    validations:
      required: true

  - type: input
    id: resource_group_name
    attributes:
      label: 🗂️ 리소스 그룹 이름
      placeholder: "dev-rg"
    validations:
      required: true

  - type: input
    id: vnet_name
    attributes:
      label: 🌐 Virtual Network 이름
      placeholder: "dev-vnet"
    validations:
      required: true

  - type: input
    id: address_space
    attributes:
      label: 📡 Address Space (CIDR)
      placeholder: '["10.0.0.0/16"]'
      description: JSON 배열 형식으로 입력
    validations:
      required: true

  - type: input
    id: vm_name
    attributes:
      label: 🖥️ 가상 머신 이름
      placeholder: "dev-vm"
    validations:
      required: true

  - type: input
    id: vm_size
    attributes:
      label: ⚙️ 가상 머신 크기 (VM Size)
      placeholder: "Standard_B1s"
    validations:
      required: true

  - type: input
    id: admin_username
    attributes:
      label: 👤 관리자 사용자 이름
      placeholder: "azureuser"
      description: 기본 로그인 계정 (비밀번호는 GitHub Secrets로 관리됨)
    validations:
      required: true
